=== Jaimeml95/Estudios-DAM/Lenguaje de Marcas y Sistemas de Gestión de la Información/Tarea 4 (Validaciones XML y JSON)/premios.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="premios">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="edicion" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="categoria" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="pelicula" type="xs:string"/>
                    <xs:element name="ganadores" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="persona" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="nombre" type="xs:string" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="aÃ±o" type="xs:gYear" use="required"/>
            <xs:attribute name="nombre" type="xs:string" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== Jaimeml95/Estudios-DAM/Lenguaje de Marcas y Sistemas de Gestión de la Información/Tarea 4 (Validaciones XML y JSON)/premios.xml
<?xml version="1.0" encoding="UTF-8"?>
<premios xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="premios.xsd">
  <edicion año="2024" nombre="Oscar">
    <categoria nombre="Mejor Película">
      <pelicula>Oppenheimer</pelicula>
      <ganadores>
        <persona>Christopher Nolan</persona>
        <persona>Emma Thomas</persona>
      </ganadores>
    </categoria>
    <categoria nombre="Mejor Director">
      <pelicula>Oppenheimer</pelicula>
      <ganadores>
        <persona>Christopher Nolan</persona>
      </ganadores>
    </categoria>
  </edicion>

  <edicion año="2024" nombre="Goya">
    <categoria nombre="Mejor Actriz">
      <pelicula>La Sociedad de la Nieve</pelicula>
      <ganadores>
        <persona>Penélope Cruz</persona>
      </ganadores>
    </categoria>
    <categoria nombre="Mejor Guion Original">
      <pelicula>La Sociedad de la Nieve</pelicula>
    </categoria>
  </edicion>
</premios>
